# Generated by Django 5.2.8 on 2026-05-26 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement File'), ('UTILITY', 'Utility Portal Export'), ('TRAVEL', 'Corporate Travel Platform API')], max_length=15)),
                ('file_name', models.CharField(max_length=255)),
                ('raw_data_snapshot', models.JSONField(help_text='Raw payload row snapshot for verification')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.company')),
            ],
        ),
    ]
