# Generated by Django 5.2.8 on 2026-05-26 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=15)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 (Direct Emissions)'), (2, 'Scope 2 (Indirect - Marketed Electricity)'), (3, 'Scope 3 (Indirect - Value Chain / Travel)')])),
                ('category', models.CharField(help_text='e.g., Diesel Fuel, Grid Electricity, Business Flights', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Original ingested value', max_digits=15)),
                ('unit', models.CharField(help_text='Original unit e.g., Liters, kWh, Gallons', max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, help_text='Calculated greenhouse metric value', max_digits=15)),
                ('normalized_unit', models.CharField(default='MTCO2e', help_text='Metric Tons of CO2 equivalent', max_length=50)),
                ('date', models.DateField(help_text='Activity or Billing cycle date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged / Suspicious')], default='PENDING', max_length=15)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False, help_text='True locks down database updates completely for audit compliance')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.company')),
                ('raw_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploads.rawupload')),
            ],
        ),
    ]
